# Generated by Django 5.2.12 on 2026-03-21 16:05

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedPDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('vendor', models.CharField(default='raritan', max_length=30)),
                ('api_url', models.CharField(max_length=200)),
                ('api_username', models.CharField(blank=True, max_length=100)),
                ('api_password', models.CharField(max_length=200)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='never', max_length=30)),
                ('pdu_model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('rated_voltage', models.CharField(blank=True, max_length=20)),
                ('rated_current', models.CharField(blank=True, max_length=20)),
                ('rated_frequency', models.CharField(blank=True, max_length=20)),
                ('rated_power', models.CharField(blank=True, max_length=20)),
                ('hw_revision', models.CharField(blank=True, max_length=50)),
                ('pdu_mac_address', models.CharField(blank=True, max_length=17)),
                ('default_gateway', models.CharField(blank=True, max_length=50)),
                ('dns_servers', models.CharField(blank=True, max_length=200)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('ntp_servers', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_pdu', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Managed PDU',
                'verbose_name_plural': 'Managed PDUs',
                'ordering': ('device',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PDUInlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('inlet_number', models.PositiveIntegerField()),
                ('inlet_name', models.CharField(blank=True, max_length=100)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('apparent_power_va', models.FloatField(blank=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('frequency_hz', models.FloatField(blank=True, null=True)),
                ('energy_wh', models.FloatField(blank=True, null=True)),
                ('energy_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_from_pdu', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('managed_pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlets', to='netbox_pdu_plugin.managedpdu')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'PDU Inlet',
                'verbose_name_plural': 'PDU Inlets',
                'ordering': ('managed_pdu', 'inlet_number'),
                'unique_together': {('managed_pdu', 'inlet_number')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PDUNetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('interface_name', models.CharField(max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('config_method', models.CharField(blank=True, max_length=10)),
                ('link_speed', models.CharField(blank=True, max_length=20)),
                ('managed_pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='netbox_pdu_plugin.managedpdu')),
            ],
            options={
                'verbose_name': 'PDU Network Interface',
                'verbose_name_plural': 'PDU Network Interfaces',
                'ordering': ('managed_pdu', 'interface_name'),
                'unique_together': {('managed_pdu', 'interface_name')},
            },
        ),
        migrations.CreateModel(
            name='PDUOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('outlet_number', models.PositiveIntegerField()),
                ('outlet_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='unknown', max_length=30)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('energy_wh', models.FloatField(blank=True, null=True)),
                ('energy_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_from_pdu', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('connected_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdu_outlets', to='dcim.device')),
                ('managed_pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='netbox_pdu_plugin.managedpdu')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'PDU Outlet',
                'verbose_name_plural': 'PDU Outlets',
                'ordering': ('managed_pdu', 'outlet_number'),
                'unique_together': {('managed_pdu', 'outlet_number')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
